version: '3'
services:
    mongodb:
        image: mongo:latest
        networks:
            - production
        container_name: mongo
        ports:
          - "27017:27017"
        volumes:
            - /home/vinicius/docker/volumes/mongo-data:/data/db
    app:
        build: .
        command: yarn dev
        ports:
          - "3000:3000"
        volumes:
            - ".:/usr/app"
networks:
    production:
        driver: bridge
